# Generated by Django 2.2 on 2021-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_address_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
