# Generated by Django 2.2 on 2021-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210227_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spelization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
