# Generated by Django 2.2 on 2021-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
