# Generated by Django 2.2 on 2021-04-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210406_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='spelization',
            new_name='specalization',
        ),
    ]
